#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer TimeStamps  {
	uint TotalTimeStamps[1];
	float TimeStamp[];
};

layout(std430, binding = 1) readonly buffer Positions {
	uint TotalPositions[1];
	vec3 Position[]; // 2D array for every object, every timestamp
};

layout(std430, binding = 2) writeonly buffer InterpolatedPositions {
	vec3 I_Positions[];
};



vec3 cubicHermite(vec3 p0, vec3 p1, vec3 m0, vec3 m1, float t) {
    float t2 = t * t;
    float t3 = t2 * t;
    return (2.0 * t3 - 3.0 * t2 + 1.0) * p0 +
           (t3 - 2.0 * t2 + t) * m0 +
           (-2.0 * t3 + 3.0 * t2) * p1 +
           (t3 - t2) * m1;
}


uniform float TimeStep;

vec3 a(float time) {
	
	return vec3(0);
}


void main() {
	uint id = gl_GlobalInvocationID.x;
	uint offset = TotalPositions[0] * id;

	for(int i = 0; i < TotalTimeStamps[0]; ++i) {
		I_Positions[i * offset] = a(TimeStamp[i]);
	}
}